---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: en
  label: Home
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: en/components
  label: Components
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: en/contributing
  label: Contributing
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: en/styles
  label: Styles
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: en/resources
  label: Resources
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: pt
  label: Inicial
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: pt/components
  label: Componentes
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: pt/estilos
  label: Estilos
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: pt/contribuindo
  label: Contribuindo
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: pt/recursos
  label: Recursos
  create: all
  match: "**/*"
  new_doc_ext: md
upload_dir: media
public_path: "/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: vuepress build -d .vuepress/dist
  publish_command: vuepress build -d .vuepress/dist
  preview_output_directory: ".vuepress/dist"
  output_directory: ".vuepress/dist"
  instant_preview_command: npm run dev
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
