backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "media" # Folder where user uploaded files should go

# This line should *not* be indented
publish_mode: editorial_workflow

collections:
  - label: "Português"
    name: "pt"
    folder: "/"
    create: true # Allow users to create new documents in this collection
    filter: {field: "language", value: "pt"}
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Linguagem", name: "language", widget: "select", options: ["en", "pt"]}
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Conteúdo", name: "body", widget: "markdown"}
  - name: "en/components"
    label: "Components"
    folder: "/en/components"
    create: true # Allow users to create new documents in this collection
    filter: {field: "language", value: "en"}
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["en", "pt"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
  - label: "Português"
    name: "pt/componentes"
    folder: "/pt/componentes"
    create: true # Allow users to create new documents in this collection
    filter: {field: "language", value: "pt"}
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Linguagem", name: "language", widget: "select", options: ["en", "pt"]}
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Conteúdo", name: "body", widget: "markdown"}